### ISSUE TITLE
Bug - App crashes when typing minus in the rent field

### ISSUE THREAD

**Issue by avihai-huji** [amit-schwartz-u/rooMe#181]
When filling in the apartment details, in the rent section, if you accidentally press the minus (-) button in the keyboard when the input is empty (i.e. after you delete the default 0.0 value), the app crashes.

The following stack trace is shown:

2020-07-02 18:36:21.395 5073-5073/com.example.roome E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.roome, PID: 5073
    java.lang.NumberFormatException: For input string: "-"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.lang.Double.parseDouble(Double.java:539)
        at com.example.roome.Roommate_searcher_tabs_classes.EditProfileRoommateSearcher$12.onTextChanged(EditProfileRoommateSearcher.java:504)
        at android.widget.TextView.sendOnTextChanged(TextView.java:10651)
        at android.widget.TextView.handleTextChanged(TextView.java:10755)
        at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:14100)
        at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1252)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:573)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:504)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:502)
        at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:849)
        at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:199)
        at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:183)
        at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:341)
        at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:85)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by avihai-huji** [comment]
Same happens for other numeric fields, such as age.

**Comment by ShaharBirzon** [comment]
fixed!
